import type { GenreKey } from '../types';

export const GENRE_LABELS: Record<GenreKey, string> = {
  action: 'Action',
  adventure: 'Adventure',
  animation: 'Animation',
  anime: 'Anime',
  comedy: 'Comedy',
  crime: 'Crime',
  documentary: 'Documentary',
  drama: 'Drama',
  family: 'Family',
  fantasy: 'Fantasy',
  history: 'History',
  horror: 'Horror',
  kids: 'Kids',
  legal: 'Legal',
  medical: 'Medical',
  music: 'Music',
  mystery: 'Mystery',
  news: 'News',
  politics: 'Politics',
  reality: 'Reality',
  romance: 'Romance',
  scifi: 'Sci-Fi',
  soap: 'Soap',
  sports: 'Sports',
  supernatural: 'Supernatural',
  talk: 'Talk',
  thriller: 'Thriller',
  war: 'War',
  western: 'Western',
};

/** Genres most people want to pick from on the taste screen (others are niche). */
export const PRIMARY_GENRES: GenreKey[] = [
  'drama',
  'comedy',
  'crime',
  'thriller',
  'mystery',
  'scifi',
  'fantasy',
  'action',
  'adventure',
  'horror',
  'supernatural',
  'romance',
  'animation',
  'anime',
  'documentary',
  'history',
  'war',
  'politics',
  'legal',
  'medical',
  'family',
  'reality',
  'sports',
  'music',
  'western',
  'kids',
  'soap',
  'talk',
  'news',
];

/** Official TMDB TV genre ids → canonical keys. */
export const TMDB_TV_GENRES: Record<number, GenreKey[]> = {
  10759: ['action', 'adventure'],
  16: ['animation'],
  35: ['comedy'],
  80: ['crime'],
  99: ['documentary'],
  18: ['drama'],
  10751: ['family'],
  10762: ['kids'],
  9648: ['mystery'],
  10763: ['news'],
  10764: ['reality'],
  10765: ['scifi', 'fantasy'],
  10766: ['soap'],
  10767: ['talk'],
  10768: ['war', 'politics'],
  37: ['western'],
};

/** Canonical key → TMDB TV genre id, for /discover queries. */
export const GENRE_TO_TMDB: Partial<Record<GenreKey, number>> = {
  action: 10759,
  adventure: 10759,
  animation: 16,
  anime: 16,
  comedy: 35,
  crime: 80,
  documentary: 99,
  drama: 18,
  family: 10751,
  kids: 10762,
  mystery: 9648,
  news: 10763,
  reality: 10764,
  scifi: 10765,
  fantasy: 10765,
  soap: 10766,
  talk: 10767,
  war: 10768,
  politics: 10768,
  western: 37,
};

const TVMAZE_GENRES: Record<string, GenreKey> = {
  action: 'action',
  adventure: 'adventure',
  anime: 'anime',
  children: 'kids',
  comedy: 'comedy',
  crime: 'crime',
  drama: 'drama',
  espionage: 'thriller',
  family: 'family',
  fantasy: 'fantasy',
  history: 'history',
  horror: 'horror',
  legal: 'legal',
  medical: 'medical',
  music: 'music',
  mystery: 'mystery',
  romance: 'romance',
  'science-fiction': 'scifi',
  sports: 'sports',
  supernatural: 'supernatural',
  thriller: 'thriller',
  war: 'war',
  western: 'western',
};

export function tvmazeGenres(genres: string[] | undefined, type?: string): GenreKey[] {
  const out = new Set<GenreKey>();
  for (const g of genres ?? []) {
    const k = TVMAZE_GENRES[g.toLowerCase()];
    if (k) out.add(k);
  }
  const t = (type ?? '').toLowerCase();
  if (t === 'animation') out.add('animation');
  if (t === 'reality' || t === 'game show') out.add('reality');
  if (t === 'documentary') out.add('documentary');
  if (t === 'talk show') out.add('talk');
  if (t === 'news') out.add('news');
  if (t === 'sports') out.add('sports');
  return [...out];
}

/** Map free-text genre names (spreadsheets, user input) onto canonical keys. */
export function parseGenreText(text: string): GenreKey[] {
  const out = new Set<GenreKey>();
  const t = text.toLowerCase();
  const rules: [RegExp, GenreKey][] = [
    [/sci[\s-]?fi|science[\s-]?fiction|scifi/, 'scifi'],
    [/fantas/, 'fantasy'],
    [/thrill|suspense/, 'thriller'],
    [/crime|heist|gangster|mafia/, 'crime'],
    [/myster|detective|whodunit/, 'mystery'],
    [/horror|scary|slasher/, 'horror'],
    [/comed|sitcom|funny/, 'comedy'],
    [/drama/, 'drama'],
    [/anime/, 'anime'],
    [/animat|cartoon/, 'animation'],
    [/docu/, 'documentary'],
    [/romanc|rom-?com|love/, 'romance'],
    [/action/, 'action'],
    [/adventur/, 'adventure'],
    [/histor|period/, 'history'],
    [/war\b|military/, 'war'],
    [/politic/, 'politics'],
    [/reality|competition/, 'reality'],
    [/sport/, 'sports'],
    [/supernatural|paranormal/, 'supernatural'],
    [/legal|law/, 'legal'],
    [/medical|hospital/, 'medical'],
    [/music|musical/, 'music'],
    [/western/, 'western'],
    [/kids|children/, 'kids'],
    [/family/, 'family'],
    [/talk/, 'talk'],
  ];
  for (const [re, key] of rules) if (re.test(t)) out.add(key);
  return [...out];
}

/**
 * Shared theme-tag vocabulary. The built-in catalog only uses these, and
 * provider keywords are folded onto them where possible, so the taste
 * profile and the recommender speak one language.
 */
export const THEME_TAGS = [
  'anti-hero',
  'based on book',
  'based on comic',
  'based on true story',
  'biography',
  'black comedy',
  'british',
  'coming of age',
  'conspiracy',
  'corporate',
  'cult',
  'cyberpunk',
  'dark',
  'dystopia',
  'ensemble cast',
  'espionage',
  'family drama',
  'feel-good',
  'friendship',
  'gangster',
  'heist',
  'high school',
  'k-drama',
  'mind-bending',
  'mockumentary',
  'monsters',
  'murder mystery',
  'mythology',
  'nostalgia',
  'period piece',
  'police procedural',
  'post-apocalyptic',
  'power struggle',
  'psychological',
  'revenge',
  'satire',
  'serial killer',
  'slow burn',
  'small town',
  'space',
  'superhero',
  'survival',
  'time travel',
  'twist ending',
  'video game adaptation',
  'workplace',
  'artificial intelligence',
  'zombies',
  'medieval',
  'royalty',
  'drugs',
  'courtroom',
  'investigative',
  'romantic comedy',
  'martial arts',
  'shonen',
  'wholesome',
  'limited series',
  'cerebral',
  'gritty',
  'witty dialogue',
  'non-linear',
  'multiverse',
  'aliens',
  'vampires',
  'magic',
  'western frontier',
  'cooking',
  'sports drama',
] as const;
export type ThemeTag = (typeof THEME_TAGS)[number];

/** Fold a free-form provider keyword onto the shared vocabulary when there's an obvious match. */
export function normalizeKeyword(raw: string): string {
  const k = raw.trim().toLowerCase();
  const aliases: Record<string, ThemeTag> = {
    'based on novel or book': 'based on book',
    'based on novel': 'based on book',
    'based on comic book': 'based on comic',
    'based on graphic novel': 'based on comic',
    'based on manga': 'based on comic',
    'true crime': 'based on true story',
    'based on a true story': 'based on true story',
    'artificial intelligence (a.i.)': 'artificial intelligence',
    'post-apocalyptic future': 'post-apocalyptic',
    'dystopian': 'dystopia',
    'time loop': 'time travel',
    'zombie': 'zombies',
    'vampire': 'vampires',
    'alien': 'aliens',
    'alien invasion': 'aliens',
    'super power': 'superhero',
    'superpower': 'superhero',
    'outer space': 'space',
    'space opera': 'space',
    'spy': 'espionage',
    'mafia': 'gangster',
    'organized crime': 'gangster',
    'drug cartel': 'drugs',
    'drug dealer': 'drugs',
    'teenager': 'coming of age',
    'high school student': 'high school',
    'sitcom': 'workplace',
    'office': 'workplace',
    'detective': 'police procedural',
    'police': 'police procedural',
    'mockumentary': 'mockumentary',
    'miniseries': 'limited series',
    'anthology': 'mind-bending',
    'parallel world': 'multiverse',
    'parallel universe': 'multiverse',
    'serial murder': 'serial killer',
    'politics': 'power struggle',
    'kingdom': 'royalty',
    'king': 'royalty',
    'queen': 'royalty',
    'witch': 'magic',
    'wizard': 'magic',
    'murder': 'murder mystery',
    'whodunit': 'murder mystery',
  };
  return aliases[k] ?? k;
}
